program: wandb_search.py
name: sex_elasticnet
method: random
metric:
  goal: maximize
  name: test_acc
parameters:
  learning_rate:
    min: 0.0000001
    max: 0.0001
  batch_size:
    distribution: q_log_uniform_values
    q: 8
    min: 32
    max: 2048
  epochs:
    values: [25, 50, 100]
  optimizer:
    value: sgd
  dropout:
    min: 0.0
    max: 0.9
  l1_lambda:
    min: 0.0
    max: 1.0
  # hidden_dims:
  #   values: [[256], [512], [512, 64, 8], [512, 256, 256, 128, 64, 32, 8]]
  k_order:
    min: 1
    max: 20
  k_degree:
    min: 1
    max: 55
  

  
    