program: KAN_wandb_cv.py
name: mrmr
method: random
metric:
  goal: maximize
  name: ACC
parameters:
  udi:
    value: 25751
  learning_rate:
    min: 0.000001
    max: 0.001
  epochs:
    value: 25
  n_layers:
    min: 1
    max: 3
  hidden_dim_ratio:
    values: [0.125, 0.25, 0.5]
  layer_size:
    values: [8, 32, 64, 256]
  mrmr:
    value: True  

  
    