program: MLP_wandb_search.py
name: mrmr
method: random
metric:
  goal: maximize
  name: ACC
parameters:
  udi:
    value: 25751
  learning_rate:
    min: 0.000001
    max: 0.001
  batch_size:
    distribution: q_log_uniform_values
    q: 8
    min: 32
    max: 256
  epochs:
    value: 25
  optimizer:
    value: Adam
  dropout:
    min: 0.0
    max: 0.9
  n_layers:
    min: 1
    max: 5
  hidden_dim_ratio:
    values: [0.125, 0.25, 0.5]
  layer_size:
    distribution: q_log_uniform_values
    q: 32
    min: 8
    max: 256
  mrmr:
    value: True  

  
    